FROM python:3-slim

ENV OPENTSDB_HOST None
ENV OPENTSDB_PORT None
ENV AUTH_USERNAME None
ENV AUTH_PASSWORD None

ENV FETCH_NUM_DAYS 1

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY config.py .
COPY jira.py .

CMD [ "python", "./jira.py" ]
